"""add pgvector

Revision ID: 4c4328de2a5c
Revises: 5178e9e6afbc
Create Date: 2026-02-23 17:04:05.098014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '4c4328de2a5c'
down_revision: Union[str, Sequence[str], None] = '5178e9e6afbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('reciperow', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reciperow', 'embedding')
    # ### end Alembic commands ###
