"""initial table creation

Revision ID: 5178e9e6afbc
Revises: 
Create Date: 2026-02-23 14:18:37.387887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5178e9e6afbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reciperow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('steps_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cuisine', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reciperow_cuisine'), 'reciperow', ['cuisine'], unique=False)
    op.create_index(op.f('ix_reciperow_title'), 'reciperow', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('measurement_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variability', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('include_spices', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_country'), 'user', ['country'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_onboarding_completed'), 'user', ['onboarding_completed'], unique=False)
    op.create_table('mealplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('request_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('stock_after_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealplan_user_id'), 'mealplan', ['user_id'], unique=False)
    op.create_table('stockitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_grams', sa.Float(), nullable=False),
    sa.Column('need_to_use', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockitem_name'), 'stockitem', ['name'], unique=False)
    op.create_index(op.f('ix_stockitem_need_to_use'), 'stockitem', ['need_to_use'], unique=False)
    op.create_index(op.f('ix_stockitem_user_id'), 'stockitem', ['user_id'], unique=False)
    op.create_table('mealentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('meal_index', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meal_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['mealplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealentry_meal_plan_id'), 'mealentry', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_mealentry_meal_type'), 'mealentry', ['meal_type'], unique=False)
    op.create_index(op.f('ix_mealentry_name'), 'mealentry', ['name'], unique=False)
    op.create_index(op.f('ix_mealentry_user_id'), 'mealentry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mealentry_user_id'), table_name='mealentry')
    op.drop_index(op.f('ix_mealentry_name'), table_name='mealentry')
    op.drop_index(op.f('ix_mealentry_meal_type'), table_name='mealentry')
    op.drop_index(op.f('ix_mealentry_meal_plan_id'), table_name='mealentry')
    op.drop_table('mealentry')
    op.drop_index(op.f('ix_stockitem_user_id'), table_name='stockitem')
    op.drop_index(op.f('ix_stockitem_need_to_use'), table_name='stockitem')
    op.drop_index(op.f('ix_stockitem_name'), table_name='stockitem')
    op.drop_table('stockitem')
    op.drop_index(op.f('ix_mealplan_user_id'), table_name='mealplan')
    op.drop_table('mealplan')
    op.drop_index(op.f('ix_user_onboarding_completed'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_country'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_reciperow_title'), table_name='reciperow')
    op.drop_index(op.f('ix_reciperow_cuisine'), table_name='reciperow')
    op.drop_table('reciperow')
    # ### end Alembic commands ###
